<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Hexagon" name="com.psx.technology.debug.c3po.content.parser.XDebugParserTest" tests="7" failures="0" timestamp="3 Aug 2011 13:47:17 GMT" time="8,874" errors="1">
  <testcase name="splitMethodNameWithClass" time="0,001" classname="com.psx.technology.debug.c3po.content.parser.XDebugParserTest"/>
  <testcase name="splitMethodNameWithClassAndNamespace" time="0,000" classname="com.psx.technology.debug.c3po.content.parser.XDebugParserTest"/>
  <testcase name="parseFileWithoutReplace" time="4,175" classname="com.psx.technology.debug.c3po.content.parser.XDebugParserTest"/>
  <testcase name="parseFileWithReplace" time="4,681" classname="com.psx.technology.debug.c3po.content.parser.XDebugParserTest">
    <error type="java.lang.AssertionError" message="expected object to not be null">
      <![CDATA[java.lang.AssertionError: expected object to not be null
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.assertNotNull(Assert.java:399)
	at org.testng.Assert.assertNotNull(Assert.java:384)
	at com.psx.technology.debug.c3po.content.parser.XDebugParserTest.parseFileWithReplace(XDebugParserTest.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1183)
	at org.testng.TestRunner.privateRun(TestRunner.java:762)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
    </error>
  </testcase>
  <testcase name="splitMethodNameInternal" time="0,000" classname="com.psx.technology.debug.c3po.content.parser.XDebugParserTest"/>
  <testcase name="handleLineDataExit" time="0,001" classname="com.psx.technology.debug.c3po.content.parser.XDebugParserTest"/>
  <testcase name="handleLineDataEntry" time="0,016" classname="com.psx.technology.debug.c3po.content.parser.XDebugParserTest"/>
</testsuite>
